# Generated by versioningit
__version__ = "3.4.11.dev4+12.g3e4c994f5b.dirty"
__build_date__ = "2025-07-30 05:47:17.582138+00:00"
__git_commit__ = "3e4c994f5b27e8612e7a5742bf43f9e6a837dad9"
__dirty__ = True
