# Generated by versioningit
__version__ = "3.4.11.dev4+3.gb6f64e41da.dirty"
__build_date__ = "2025-07-29 18:32:48.039332+00:00"
__git_commit__ = "b6f64e41da1f5bd15c47308722b1e674b929efdd"
__dirty__ = True
