# Generated by versioningit
__version__ = "3.4.11.dev4+11.g4a53526e35.dirty"
__build_date__ = "2025-07-30 05:44:31.974609+00:00"
__git_commit__ = "4a53526e35a711f6c03fd673bcc6a3f3fb473ef2"
__dirty__ = True
